using System.Collections;
using UnityEngine;
using NSFGrant.Logging;

namespace NSFGrant.Interaction
{
    /// <summary>
    /// Hand-rolled VR locomotion for the study rig. No XR Interaction
    /// Toolkit or Meta Interaction SDK is installed (Packages/manifest.json
    /// only carries com.meta.xr.sdk.core), and the hall spans a ~32 m
    /// hub-to-room arc - far past any realistic Quest Guardian space - so
    /// virtual locomotion is required to reach the rooms at all.
    ///
    /// Controls follow the standard Quest scheme:
    ///   - LEFT thumbstick: smooth walk, relative to where the head faces,
    ///     driven through a CharacterController so walls/columns collide
    ///     normally instead of letting the participant phase through.
    ///   - RIGHT thumbstick forward (hold + release): parabolic teleport
    ///     arc with a green/red landing reticle; valid only on a
    ///     TeleportSurface. Trigger volumes (SdgStation etc.) are ignored
    ///     by the arc - they are data sensors, not geometry.
    ///   - RIGHT thumbstick left/right flick: snap turn, pivoting around
    ///     the head position (not the rig origin, which would swing the
    ///     participant sideways through the room).
    ///
    /// Teleports and snap turns bracket a brief fade-to-black (comfort,
    /// and it keeps the viewpoint jump from looking like a gaze artifact),
    /// and both are logged via StudyEventLogger so VR navigation stays
    /// analyzable; smooth walking needs no discrete event because the
    /// per-frame head-position stream already captures it continuously.
    /// </summary>
    public class VRLocomotion : MonoBehaviour
    {
        [Tooltip("The rig root that gets moved/rotated (the object PlatformRigSwitcher toggles).")]
        [SerializeField] private Transform rigRoot;

        [Tooltip("Aim origin/direction for the teleport arc (right controller). Falls back to centerEye if unset.")]
        [SerializeField] private Transform controllerAnchor;

        [Tooltip("Head anchor: smooth-move direction reference, snap-turn pivot, fade-quad parent.")]
        [SerializeField] private Transform centerEye;

        [Header("Smooth movement (left stick)")]
        [SerializeField] private float moveSpeed = 2.0f;

        [Header("Teleport (right stick forward)")]
        [SerializeField] private float arcSpeed = 11f;
        [SerializeField] private float arcGravity = 12f;
        [SerializeField] private int arcSegments = 30;
        [SerializeField] private float segmentStep = 0.05f;

        [Header("Snap turn (right stick left/right)")]
        [SerializeField] private float snapTurnAngle = 45f;

        [Header("Comfort")]
        [SerializeField] private float fadeSeconds = 0.12f;
        [SerializeField] private float thumbstickDeadzone = 0.35f;
        [Tooltip("Peripheral vignette strength while stick-walking (0 disables).")]
        [SerializeField, Range(0f, 1f)] private float vignetteStrength = 0.75f;

        private CharacterController _body;
        private LineRenderer _arc;
        private Transform _reticle;
        private Renderer[] _reticleParts;
        private Material _arcValidMat;
        private Material _arcInvalidMat;
        private Material _reticleValidMat;
        private Material _reticleInvalidMat;

        private Material _fadeMaterial;
        private float _fadeAlpha;
        private Coroutine _fadeRoutine;

        private Material _vignetteMaterial;
        private float _vignetteCurrent;
        private bool _stickWalking;

        private bool _aiming;
        private bool _hasValidTarget;
        private Vector3 _landingPoint;
        private bool _turnArmed = true;

        private void Awake()
        {
            // Self-wire at runtime so the component still works even if the
            // scene was generated by an older builder that didn't set these.
            if (rigRoot == null)
            {
                rigRoot = transform;
            }
            var ovrRig = rigRoot.GetComponentInChildren<OVRCameraRig>(true);
            if (centerEye == null && ovrRig != null)
            {
                centerEye = ovrRig.centerEyeAnchor;
            }
            if (controllerAnchor == null && ovrRig != null)
            {
                controllerAnchor = ovrRig.rightControllerAnchor;
            }
            if (controllerAnchor == null)
            {
                controllerAnchor = centerEye;
            }

            // Body collider for smooth walking - without it the stick would
            // glide the participant straight through walls.
            _body = rigRoot.GetComponent<CharacterController>();
            if (_body == null)
            {
                _body = rigRoot.gameObject.AddComponent<CharacterController>();
                _body.height = 1.8f;
                _body.radius = 0.3f;
                _body.center = new Vector3(0f, 0.9f, 0f);
            }

            BuildArcVisuals();
            BuildFadeQuad();
            BuildVignette();
        }

        private void Start()
        {
            // Arrive gently: open on black and reveal the hall, instead of
            // popping the participant into the world mid-frame.
            _fadeAlpha = 1f;
            ApplyFadeAlpha();
            _fadeRoutine = StartCoroutine(Fade(0f, 0.8f));
        }

        private void Update()
        {
            HandleSmoothMove();
            HandleTeleportAim();
            HandleSnapTurn();
            UpdateVignette();
        }

        /// <summary>Left stick: walk in the direction the head faces.</summary>
        private void HandleSmoothMove()
        {
            if (centerEye == null || _body == null || !_body.enabled)
            {
                return;
            }

            Vector2 stick = XRInputBridge.GetThumbstick(XRInputBridge.Hand.Left);
            _stickWalking = stick.magnitude >= thumbstickDeadzone;
            if (!_stickWalking)
            {
                // Still apply gravity so the capsule stays settled on the floor.
                _body.Move(Vector3.down * (3f * Time.deltaTime));
                return;
            }

            Vector3 forward = centerEye.forward;
            forward.y = 0f;
            forward.Normalize();
            Vector3 right = centerEye.right;
            right.y = 0f;
            right.Normalize();

            Vector3 motion = (forward * stick.y + right * stick.x) * moveSpeed;
            _body.Move((motion + Vector3.down * 3f) * Time.deltaTime);
        }

        /// <summary>
        /// Right stick pushed mostly-forward: aim the arc; release: teleport.
        /// The mostly-forward check keeps diagonal input from aiming and
        /// snap-turning at once.
        /// </summary>
        private void HandleTeleportAim()
        {
            if (controllerAnchor == null)
            {
                return;
            }

            Vector2 stick = XRInputBridge.GetThumbstick(XRInputBridge.Hand.Right);
            bool wantsAim = _aiming
                ? stick.y > thumbstickDeadzone * 0.6f            // hysteresis while held
                : stick.y > thumbstickDeadzone && stick.y >= Mathf.Abs(stick.x);

            if (wantsAim)
            {
                _aiming = true;
                EvaluateArc();
                _arc.enabled = true;
                _reticle.gameObject.SetActive(_hasValidTarget);
            }
            else if (_aiming)
            {
                _aiming = false;
                _arc.enabled = false;
                _reticle.gameObject.SetActive(false);
                if (_hasValidTarget)
                {
                    Teleport(_landingPoint);
                }
            }
        }

        /// <summary>
        /// Samples a projectile arc from the controller and walks it
        /// segment-by-segment with Physics.Linecast until it hits real
        /// geometry - trigger volumes (station sensors) are ignored, since
        /// an invisible data sensor must never block movement. The first
        /// hit is the landing point, valid only on a TeleportSurface.
        /// </summary>
        private void EvaluateArc()
        {
            Vector3 origin = controllerAnchor.position;
            Vector3 velocity = controllerAnchor.forward * arcSpeed;
            var points = new Vector3[arcSegments];
            points[0] = origin;

            _hasValidTarget = false;
            Vector3 previous = origin;
            int drawn = 1;
            for (int i = 1; i < arcSegments; i++)
            {
                float t = i * segmentStep;
                Vector3 next = origin + velocity * t + 0.5f * Vector3.down * arcGravity * t * t;

                if (Physics.Linecast(previous, next, out RaycastHit hit,
                        Physics.DefaultRaycastLayers, QueryTriggerInteraction.Ignore))
                {
                    points[drawn++] = hit.point;
                    _hasValidTarget = hit.collider.GetComponentInParent<TeleportSurface>() != null;
                    _landingPoint = hit.point;
                    break;
                }

                points[drawn++] = next;
                previous = next;
            }

            _arc.positionCount = drawn;
            _arc.SetPositions(points);
            _arc.material = _hasValidTarget ? _arcValidMat : _arcInvalidMat;

            if (_hasValidTarget)
            {
                _reticle.position = _landingPoint + Vector3.up * 0.02f;
            }
            Material reticleMat = _hasValidTarget ? _reticleValidMat : _reticleInvalidMat;
            foreach (Renderer part in _reticleParts)
            {
                part.sharedMaterial = reticleMat;
            }
        }

        /// <summary>Right stick left/right flick (not while aiming).</summary>
        private void HandleSnapTurn()
        {
            Vector2 stick = XRInputBridge.GetThumbstick(XRInputBridge.Hand.Right);

            if (Mathf.Abs(stick.x) < thumbstickDeadzone)
            {
                _turnArmed = true;
                return;
            }
            if (!_turnArmed || _aiming || Mathf.Abs(stick.x) < Mathf.Abs(stick.y))
            {
                return;
            }
            _turnArmed = false;

            float angle = stick.x > 0f ? snapTurnAngle : -snapTurnAngle;
            StartCoroutine(SnapTurnRoutine(angle));
        }

        private void Teleport(Vector3 destination)
        {
            if (_fadeRoutine != null)
            {
                StopCoroutine(_fadeRoutine);
            }
            _fadeRoutine = StartCoroutine(TeleportRoutine(destination));
        }

        private IEnumerator TeleportRoutine(Vector3 destination)
        {
            Vector3 from = rigRoot.position;
            yield return Fade(1f, fadeSeconds);

            // Land the PARTICIPANT'S HEAD on the reticle, not the rig
            // origin - with room-scale tracking the head can be meters from
            // the origin, and teleporting the origin would drop the player
            // visibly short of (or past) the point they aimed at. The
            // CharacterController is toggled off around the warp so it
            // can't veto the position change.
            Vector3 headOffset = centerEye != null
                ? centerEye.position - rigRoot.position
                : Vector3.zero;
            var target = new Vector3(
                destination.x - headOffset.x,
                rigRoot.position.y,
                destination.z - headOffset.z);

            bool hadBody = _body != null && _body.enabled;
            if (hadBody)
            {
                _body.enabled = false;
            }
            rigRoot.position = target;
            if (hadBody)
            {
                _body.enabled = true;
            }

            StudyEventLogger.Instance?.LogWorldEvent("teleport", "",
                $"from_x={from.x:F2};from_z={from.z:F2}", destination);

            yield return Fade(0f, fadeSeconds);
        }

        private IEnumerator SnapTurnRoutine(float angle)
        {
            yield return Fade(1f, fadeSeconds * 0.6f);

            // Pivot around the head, not the rig origin, so the view spins
            // in place instead of swinging the participant across the room.
            Vector3 pivot = centerEye != null ? centerEye.position : rigRoot.position;
            bool hadBody = _body != null && _body.enabled;
            if (hadBody)
            {
                _body.enabled = false;
            }
            rigRoot.RotateAround(pivot, Vector3.up, angle);
            if (hadBody)
            {
                _body.enabled = true;
            }
            StudyEventLogger.Instance?.LogEvent("vr_snap_turn", "", $"degrees={angle:F0}");

            yield return Fade(0f, fadeSeconds * 0.6f);
        }

        private IEnumerator Fade(float target, float duration)
        {
            float start = _fadeAlpha;
            float t = 0f;
            while (t < duration)
            {
                t += Time.unscaledDeltaTime;
                _fadeAlpha = duration > 0f ? Mathf.Lerp(start, target, t / duration) : target;
                ApplyFadeAlpha();
                yield return null;
            }
            _fadeAlpha = target;
            ApplyFadeAlpha();
        }

        private void ApplyFadeAlpha()
        {
            if (_fadeMaterial == null)
            {
                return;
            }
            Color c = _fadeMaterial.color;
            c.a = _fadeAlpha;
            _fadeMaterial.color = c;
        }

        private void BuildArcVisuals()
        {
            var arcGo = new GameObject("TeleportArc");
            arcGo.transform.SetParent(transform, false);
            _arc = arcGo.AddComponent<LineRenderer>();
            _arc.startWidth = 0.03f;
            _arc.endWidth = 0.03f;
            _arc.useWorldSpace = true;
            _arc.positionCount = 0;
            _arc.enabled = false;
            _arc.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            _arc.receiveShadows = false;

            _arcValidMat = MakeUnlitMaterial(new Color(0.3f, 0.9f, 0.5f, 0.9f));
            _arcInvalidMat = MakeUnlitMaterial(new Color(0.9f, 0.3f, 0.3f, 0.7f));
            _arc.material = _arcInvalidMat;

            // Landing reticle: a thin ring with a small center dot reads as
            // a "target" rather than the old opaque manhole-cover disc.
            var reticleGo = new GameObject("TeleportReticle");
            reticleGo.transform.SetParent(transform, false);
            _reticle = reticleGo.transform;
            _reticleValidMat = MakeUnlitMaterial(new Color(0.3f, 0.9f, 0.5f, 0.75f));
            _reticleInvalidMat = MakeUnlitMaterial(new Color(0.9f, 0.3f, 0.3f, 0.6f));

            var ringGo = new GameObject("Ring");
            ringGo.transform.SetParent(reticleGo.transform, false);
            var ring = ringGo.AddComponent<LineRenderer>();
            ring.useWorldSpace = false;
            ring.loop = true;
            const int ringPoints = 28;
            const float ringRadius = 0.24f;
            ring.positionCount = ringPoints;
            for (int i = 0; i < ringPoints; i++)
            {
                float a = i * Mathf.PI * 2f / ringPoints;
                ring.SetPosition(i, new Vector3(Mathf.Cos(a) * ringRadius, 0f, Mathf.Sin(a) * ringRadius));
            }
            ring.startWidth = 0.02f;
            ring.endWidth = 0.02f;
            ring.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            ring.receiveShadows = false;

            var dotGo = GameObject.CreatePrimitive(PrimitiveType.Cylinder);
            dotGo.name = "Dot";
            Destroy(dotGo.GetComponent<Collider>());
            dotGo.transform.SetParent(reticleGo.transform, false);
            dotGo.transform.localScale = new Vector3(0.07f, 0.006f, 0.07f);
            var dotRenderer = dotGo.GetComponent<MeshRenderer>();
            dotRenderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            dotRenderer.receiveShadows = false;

            _reticleParts = new Renderer[] { ring, dotRenderer };
            foreach (Renderer part in _reticleParts)
            {
                part.sharedMaterial = _reticleValidMat;
            }
            reticleGo.SetActive(false);
        }

        /// <summary>
        /// Small quad in front of the eye running NSFGrant/ComfortVignette;
        /// UpdateVignette animates its strength with stick movement.
        /// </summary>
        private void BuildVignette()
        {
            if (centerEye == null || vignetteStrength <= 0f)
            {
                return;
            }
            var shader = Shader.Find("NSFGrant/ComfortVignette");
            if (shader == null)
            {
                Debug.LogWarning("[VRLocomotion] NSFGrant/ComfortVignette shader not found; " +
                                  "comfort vignette disabled.");
                return;
            }

            var quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            quad.name = "ComfortVignette";
            Destroy(quad.GetComponent<Collider>());
            quad.transform.SetParent(centerEye, false);
            quad.transform.localPosition = new Vector3(0f, 0f, 0.35f);
            quad.transform.localRotation = Quaternion.identity;
            // Sized so the visible FOV maps to roughly uv-radius ~0.36 at
            // 0.35 m - the ramp lives in the periphery, not center view.
            quad.transform.localScale = new Vector3(1.6f, 1.6f, 1f);

            var renderer = quad.GetComponent<MeshRenderer>();
            renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            _vignetteMaterial = new Material(shader);
            _vignetteMaterial.SetFloat("_Strength", 0f);
            renderer.sharedMaterial = _vignetteMaterial;
        }

        /// <summary>
        /// Ramps the vignette in quickly when stick-walking starts and out
        /// more slowly when it stops (an abrupt release flicker would be
        /// more noticeable than the vignette itself).
        /// </summary>
        private void UpdateVignette()
        {
            if (_vignetteMaterial == null)
            {
                return;
            }
            float target = _stickWalking ? vignetteStrength : 0f;
            float rate = target > _vignetteCurrent ? 6f : 2.5f;
            _vignetteCurrent = Mathf.MoveTowards(_vignetteCurrent, target, rate * Time.deltaTime);
            _vignetteMaterial.SetFloat("_Strength", _vignetteCurrent);
        }

        /// <summary>
        /// A large, camera-facing quad parented close in front of the eye
        /// for the fade-to-black transition (VR has no screen-space IMGUI
        /// to fade instead). Placed well past any plausible near-clip
        /// distance and oversized so it fills the FOV regardless of
        /// headset - precision doesn't matter for a solid color fade.
        /// </summary>
        private void BuildFadeQuad()
        {
            if (centerEye == null)
            {
                return;
            }
            var quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            quad.name = "VRFadeQuad";
            Destroy(quad.GetComponent<Collider>());
            quad.transform.SetParent(centerEye, false);
            quad.transform.localPosition = new Vector3(0f, 0f, 0.4f);
            quad.transform.localRotation = Quaternion.identity;
            quad.transform.localScale = Vector3.one * 5f;

            var renderer = quad.GetComponent<MeshRenderer>();
            renderer.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
            renderer.receiveShadows = false;
            _fadeMaterial = MakeUnlitMaterial(new Color(0f, 0f, 0f, 0f));
            renderer.sharedMaterial = _fadeMaterial;
        }

        /// <summary>
        /// NSFGrant/UnlitTransparentColor renders both faces (Cull Off), so
        /// quad/plane orientation doesn't matter here. Falls back to
        /// Sprites/Default if the shader is missing.
        /// </summary>
        private static Material MakeUnlitMaterial(Color color)
        {
            var shader = Shader.Find("NSFGrant/UnlitTransparentColor");
            var material = new Material(shader != null ? shader : Shader.Find("Sprites/Default"));
            material.SetColor("_Color", color);
            return material;
        }
    }
}
