using System;
using System.Collections.Generic;
using System.IO;
using NSFGrant.Stations;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace NSFGrant.EditorTools
{
    /// <summary>
    /// Writes 1920x1080 PNGs of the study scenes for the IRB location set.
    /// Menu: Tools &gt; Capture Scene Screenshots.
    /// Batch: -executeMethod NSFGrant.EditorTools.SceneScreenshotCapture.CaptureAll
    ///
    /// Opens each scene in the Build Settings list, plus the generated
    /// primary scenes when they exist on disk, and renders a temporary
    /// camera. Scene files and other assets are not saved.
    /// </summary>
    public static class SceneScreenshotCapture
    {
        public const int Width = 1920;
        public const int Height = 1080;

        // Standing eye height used when an XR eye anchor is still on the
        // floor (edit mode has no headset tracking) and for interior shots.
        private const float EyeHeight = 1.6f;

        // Generated by the NSF Grant menu / CiTools. Not committed.
        private static readonly string[] PrimaryScenePaths =
        {
            "Assets/Scenes/DiscoveryHall.unity",
            "Assets/Scenes/AttentionStudy.unity"
        };

        private const string NoScenesHint =
            "No scenes to capture. Scene files are generated and are not in the " +
            "repository, and ProjectSettings/EditorBuildSettings.asset is not " +
            "committed, so Build Settings starts empty. Generate the study scene " +
            "with NSF Grant > Build Discovery Hall Scene (Assets/Scenes/DiscoveryHall.unity) " +
            "or -executeMethod NSFGrant.EditorTools.DiscoveryHallBuilder.BuildDiscoveryHall. " +
            "The optional gaze-test scene is NSF Grant > Build Sample Scene " +
            "(Assets/Scenes/AttentionStudy.unity). ./scripts/unity-tasks.sh setup does " +
            "the full project setup, including the Discovery Hall scene and Build Settings.";

        private struct Shot
        {
            public string Location;
            public Vector3 Position;
            public Quaternion Rotation;
            public Camera Template;
        }

        [MenuItem("Tools/Capture Scene Screenshots")]
        public static void CaptureFromMenu()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            {
                Debug.Log("[SceneScreenshotCapture] Cancelled.");
                return;
            }

            int count = CaptureAllInternal(restoreOpenScenes: true);
            string folder = OutputDirectory();
            EditorUtility.DisplayDialog(
                "Scene screenshots",
                count > 0
                    ? "Saved " + count + " PNG(s) to:\n" + folder
                    : "No screenshots were written.\n\n" + NoScenesHint,
                "OK");
        }

        /// <summary>
        /// Batch-mode entry point. Needs a GPU: do not pass -nographics.
        /// Exits the editor with code 1 when nothing was written.
        /// </summary>
        public static void CaptureAll()
        {
            int count = CaptureAllInternal(restoreOpenScenes: false);
            if (count <= 0 && Application.isBatchMode)
            {
                EditorApplication.Exit(1);
            }
        }

        private static int CaptureAllInternal(bool restoreOpenScenes)
        {
            var previous = restoreOpenScenes
                ? EditorSceneManager.GetSceneManagerSetup()
                : null;
            int saved = 0;
            try
            {
                List<string> paths = CollectScenePaths();
                if (paths.Count == 0)
                {
                    Debug.LogError("[SceneScreenshotCapture] " + NoScenesHint);
                    return 0;
                }

                Directory.CreateDirectory(OutputDirectory());
                for (int i = 0; i < paths.Count; i++)
                {
                    string path = paths[i];
                    EditorUtility.DisplayProgressBar(
                        "Scene screenshots", path, (float)i / paths.Count);

                    Scene scene;
                    try
                    {
                        scene = EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
                    }
                    catch (Exception e)
                    {
                        Debug.LogError(
                            "[SceneScreenshotCapture] Could not open " + path + ": " + e.Message);
                        continue;
                    }

                    if (!scene.IsValid() || !scene.isLoaded)
                    {
                        Debug.LogError("[SceneScreenshotCapture] Could not open " + path + ".");
                        continue;
                    }

                    saved += CaptureOpenScene(scene);
                }

                Debug.Log("[SceneScreenshotCapture] Wrote " + saved +
                          " screenshot(s) to " + OutputDirectory());
                return saved;
            }
            finally
            {
                EditorUtility.ClearProgressBar();
                if (previous != null && previous.Length > 0)
                {
                    try
                    {
                        EditorSceneManager.RestoreSceneManagerSetup(previous);
                    }
                    catch (Exception e)
                    {
                        Debug.LogWarning(
                            "[SceneScreenshotCapture] Could not restore the previously " +
                            "open scenes: " + e.Message);
                    }
                }
            }
        }

        private static List<string> CollectScenePaths()
        {
            var paths = new List<string>();
            var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            EditorBuildSettingsScene[] listed = EditorBuildSettings.scenes
                ?? Array.Empty<EditorBuildSettingsScene>();
            foreach (EditorBuildSettingsScene entry in listed)
            {
                if (entry == null || string.IsNullOrEmpty(entry.path))
                {
                    continue;
                }

                string path = entry.path.Replace('\\', '/');
                if (!seen.Add(path))
                {
                    continue;
                }

                if (!ProjectFileExists(path))
                {
                    Debug.LogError(
                        "[SceneScreenshotCapture] Build Settings lists '" + path +
                        "', but that file is not on disk. Skipped.");
                    continue;
                }

                paths.Add(path);
            }

            foreach (string primary in PrimaryScenePaths)
            {
                if (!seen.Add(primary) || !ProjectFileExists(primary))
                {
                    continue;
                }

                paths.Add(primary);
            }

            return paths;
        }

        private static int CaptureOpenScene(Scene scene)
        {
            bool dirtyBefore = scene.isDirty;
            List<Shot> shots = CollectShots(scene);
            if (shots.Count == 0)
            {
                Debug.LogWarning(
                    "[SceneScreenshotCapture] No cameras, spawn points, stations, " +
                    "or geometry to frame in " + scene.path + ".");
                DiscardIfWeDirtied(scene, dirtyBefore);
                return 0;
            }

            shots.Sort((a, b) => string.CompareOrdinal(a.Location, b.Location));
            var used = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            int saved = 0;
            foreach (Shot shot in shots)
            {
                Debug.Log("[SceneScreenshotCapture] " + scene.name + " / " + shot.Location +
                          " at " + shot.Position.ToString("F2"));
                if (SaveShot(scene, shot, used))
                {
                    saved++;
                }
            }

            DiscardIfWeDirtied(scene, dirtyBefore);
            return saved;
        }

        /// <summary>
        /// Discovery Hall locations, once the builder has generated the scene:
        /// desktop_spawn and vr_spawn from the two rig cameras (the VR eye is
        /// lifted to eye height when it is still on the floor), CentralHub
        /// looking at the waterfall, and one interior view per SdgStation
        /// (SDG04_QualityEducation, SDG11_SustainableCities,
        /// SDG13_ClimateAction) aimed at that room's exhibit wall.
        /// The sample scene contributes vr_spawn, looking at its targets.
        /// </summary>
        private static List<Shot> CollectShots(Scene scene)
        {
            var shots = new List<Shot>();

            foreach (Camera cam in UnityEngine.Object.FindObjectsByType<Camera>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!BelongsToScene(cam.gameObject, scene))
                {
                    continue;
                }

                if (cam.cameraType != CameraType.Game && cam.cameraType != CameraType.VR)
                {
                    continue;
                }

                if (IsSideEye(cam.transform))
                {
                    continue;
                }

                Vector3 position = cam.transform.position;
                if (position.y < 0.75f && HasAncestor(cam.transform, "OVRCameraRig"))
                {
                    position.y = EyeHeight;
                }

                shots.Add(new Shot
                {
                    Location = LocationNameForCamera(cam),
                    Position = position,
                    Rotation = cam.transform.rotation,
                    Template = cam
                });
            }

            foreach (Transform transform in UnityEngine.Object.FindObjectsByType<Transform>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!BelongsToScene(transform.gameObject, scene) || !LooksLikeSpawn(transform.name))
                {
                    continue;
                }

                if (transform.GetComponentInChildren<Camera>(true) != null)
                {
                    continue;
                }

                Vector3 position = transform.position;
                if (position.y < 0.75f)
                {
                    position.y = EyeHeight;
                }

                Quaternion rotation = transform.rotation;
                if (IsNearExisting(shots, position, rotation))
                {
                    continue;
                }

                shots.Add(new Shot
                {
                    Location = Slug(transform.name),
                    Position = position,
                    Rotation = rotation,
                    Template = null
                });
            }

            // Builder layout: station local +Z points back at the hub, the
            // doorway is at local z = 6, and the exhibit wall is at local z ~ 0.
            // The camera stands just inside the door looking at that wall.
            foreach (SdgStation station in UnityEngine.Object.FindObjectsByType<SdgStation>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!BelongsToScene(station.gameObject, scene))
                {
                    continue;
                }

                Vector3 position = station.transform.TransformPoint(new Vector3(0f, EyeHeight, 5f));
                Vector3 target = station.transform.TransformPoint(new Vector3(0f, 1.7f, 0f));
                shots.Add(new Shot
                {
                    Location = Slug(station.StationId),
                    Position = position,
                    Rotation = Quaternion.LookRotation(target - position, Vector3.up),
                    Template = null
                });
            }

            foreach (Transform transform in UnityEngine.Object.FindObjectsByType<Transform>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!BelongsToScene(transform.gameObject, scene) || transform.name != "CentralHub")
                {
                    continue;
                }

                // Off the welcome plinth, looking toward the south-wall waterfall.
                Vector3 position = transform.TransformPoint(new Vector3(1.6f, EyeHeight, 1.2f));
                Vector3 target = transform.TransformPoint(new Vector3(0f, 1.7f, -5f));
                shots.Add(new Shot
                {
                    Location = "CentralHub",
                    Position = position,
                    Rotation = Quaternion.LookRotation(target - position, Vector3.up),
                    Template = null
                });
                break;
            }

            if (shots.Count == 0 &&
                TryBoundsOverview(scene, out Vector3 overviewPos, out Quaternion overviewRot))
            {
                shots.Add(new Shot
                {
                    Location = "overview",
                    Position = overviewPos,
                    Rotation = overviewRot,
                    Template = null
                });
            }

            return shots;
        }

        private static bool SaveShot(Scene scene, Shot shot, HashSet<string> usedNames)
        {
            GameObject camGo = null;
            RenderTexture rt = null;
            Texture2D tex = null;
            RenderTexture previous = RenderTexture.active;
            try
            {
                camGo = EditorUtility.CreateGameObjectWithHideFlags(
                    "SceneScreenshotCamera",
                    HideFlags.HideAndDontSave,
                    typeof(Camera));
                EnsureUrpCameraData(camGo);
                rt = new RenderTexture(
                    Width, Height, 24, RenderTextureFormat.ARGB32, RenderTextureReadWrite.sRGB)
                {
                    antiAliasing = 4
                };
                rt.Create();

                var cam = camGo.GetComponent<Camera>();
                ApplyShot(cam, shot);
                cam.targetTexture = rt;
                cam.aspect = (float)Width / Height;
                cam.Render();

                RenderTexture.active = rt;
                tex = new Texture2D(Width, Height, TextureFormat.RGB24, false);
                tex.ReadPixels(new Rect(0f, 0f, Width, Height), 0, 0);
                tex.Apply();

                string location = Unique(usedNames, shot.Location);
                string sceneName = Slug(Path.GetFileNameWithoutExtension(scene.path));
                string path = Path.Combine(OutputDirectory(), sceneName + "_" + location + ".png");
                File.WriteAllBytes(path, tex.EncodeToPNG());
                Debug.Log("[SceneScreenshotCapture] " + path.Replace('\\', '/'));
                return true;
            }
            catch (Exception e)
            {
                Debug.LogError(
                    "[SceneScreenshotCapture] Failed '" + shot.Location + "' in " +
                    scene.path + ": " + e.Message +
                    " Capture needs a graphics device; do not pass -nographics.");
                return false;
            }
            finally
            {
                RenderTexture.active = previous;
                if (tex != null)
                {
                    UnityEngine.Object.DestroyImmediate(tex);
                }

                if (rt != null)
                {
                    rt.Release();
                    UnityEngine.Object.DestroyImmediate(rt);
                }

                if (camGo != null)
                {
                    UnityEngine.Object.DestroyImmediate(camGo);
                }
            }
        }

        // After URP is assigned, a camera with no UniversalAdditionalCameraData
        // renders empty. The component is absent until setup has imported URP.
        private static void EnsureUrpCameraData(GameObject camGo)
        {
            Type urpType = null;
            foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                urpType = assembly.GetType(
                    "UnityEngine.Rendering.Universal.UniversalAdditionalCameraData", false);
                if (urpType != null)
                {
                    break;
                }
            }

            if (urpType == null || camGo.GetComponent(urpType) != null)
            {
                return;
            }

            camGo.AddComponent(urpType);
        }

        private static void ApplyShot(Camera cam, Shot shot)
        {
            cam.enabled = false;
            cam.stereoTargetEye = StereoTargetEyeMask.None;
            cam.transform.SetPositionAndRotation(shot.Position, shot.Rotation);
            cam.rect = new Rect(0f, 0f, 1f, 1f);

            Camera template = shot.Template;
            if (template != null)
            {
                cam.orthographic = template.orthographic;
                cam.orthographicSize = template.orthographicSize;
                cam.fieldOfView = template.fieldOfView > 1f ? template.fieldOfView : 60f;
                cam.nearClipPlane = template.nearClipPlane;
                cam.farClipPlane = Mathf.Max(template.farClipPlane, 50f);
                cam.cullingMask = template.cullingMask;
                cam.clearFlags = template.clearFlags;
                cam.backgroundColor = template.backgroundColor;
                return;
            }

            cam.orthographic = false;
            cam.fieldOfView = 60f;
            cam.nearClipPlane = 0.1f;
            cam.farClipPlane = 100f;
            cam.cullingMask = ~0;
            cam.clearFlags = CameraClearFlags.Skybox;
            cam.backgroundColor = new Color(0.16f, 0.17f, 0.19f);
        }

        private static void DiscardIfWeDirtied(Scene scene, bool dirtyBefore)
        {
            if (!scene.IsValid() || dirtyBefore || !scene.isDirty)
            {
                return;
            }

            string path = scene.path;
            Debug.LogError(
                "[SceneScreenshotCapture] Capture marked " + path +
                " dirty. Reloading from disk; the scene file was not saved.");
            if (!string.IsNullOrEmpty(path))
            {
                EditorSceneManager.OpenScene(path, OpenSceneMode.Single);
            }
        }

        private static bool TryBoundsOverview(Scene scene, out Vector3 position, out Quaternion rotation)
        {
            position = default;
            rotation = Quaternion.identity;
            bool any = false;
            Bounds bounds = default;
            foreach (Renderer renderer in UnityEngine.Object.FindObjectsByType<Renderer>(
                         FindObjectsInactive.Include, FindObjectsSortMode.None))
            {
                if (!BelongsToScene(renderer.gameObject, scene))
                {
                    continue;
                }

                if (!any)
                {
                    bounds = renderer.bounds;
                    any = true;
                }
                else
                {
                    bounds.Encapsulate(renderer.bounds);
                }
            }

            if (!any)
            {
                return false;
            }

            Vector3 center = bounds.center;
            float distance = Mathf.Max(bounds.extents.magnitude * 1.6f, 2f);
            position = center + new Vector3(0f, bounds.extents.y * 0.35f, -distance);
            Vector3 forward = center - position;
            if (forward.sqrMagnitude < 0.001f)
            {
                forward = Vector3.forward;
            }

            rotation = Quaternion.LookRotation(forward, Vector3.up);
            return true;
        }

        private static string LocationNameForCamera(Camera cam)
        {
            if (cam.gameObject.name == "DesktopCamera" || HasAncestor(cam.transform, "DesktopPlayer"))
            {
                return "desktop_spawn";
            }

            if (HasAncestor(cam.transform, "OVRCameraRig"))
            {
                return "vr_spawn";
            }

            Transform named = cam.transform;
            if (IsGenericCameraName(named.name) && named.parent != null)
            {
                named = named.parent;
            }

            return Slug(named.name);
        }

        private static bool IsGenericCameraName(string name)
        {
            return name == "Camera" || name == "Main Camera" || name == "MainCamera";
        }

        private static bool LooksLikeSpawn(string name)
        {
            if (name.IndexOf("Spawn", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                return true;
            }

            return name == "PlayerStart" || name == "StartPoint" || name == "StartPosition";
        }

        private static bool IsSideEye(Transform transform)
        {
            for (Transform p = transform; p != null; p = p.parent)
            {
                if (p.name.IndexOf("LeftEye", StringComparison.OrdinalIgnoreCase) >= 0 ||
                    p.name.IndexOf("RightEye", StringComparison.OrdinalIgnoreCase) >= 0)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool HasAncestor(Transform transform, string name)
        {
            for (Transform p = transform; p != null; p = p.parent)
            {
                if (p.name == name)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool IsNearExisting(List<Shot> shots, Vector3 position, Quaternion rotation)
        {
            Vector3 forward = rotation * Vector3.forward;
            foreach (Shot shot in shots)
            {
                if ((shot.Position - position).sqrMagnitude > 0.25f)
                {
                    continue;
                }

                if (Vector3.Dot(shot.Rotation * Vector3.forward, forward) > 0.98f)
                {
                    return true;
                }
            }

            return false;
        }

        private static bool BelongsToScene(GameObject go, Scene scene)
        {
            if (go.scene != scene)
            {
                return false;
            }

            HideFlags flags = go.hideFlags;
            return (flags & HideFlags.DontSave) == 0 && (flags & HideFlags.HideAndDontSave) == 0;
        }

        private static bool ProjectFileExists(string assetPath)
        {
            if (File.Exists(assetPath))
            {
                return true;
            }

            string root = Path.GetDirectoryName(Application.dataPath);
            return !string.IsNullOrEmpty(root) && File.Exists(Path.Combine(root, assetPath));
        }

        private static string OutputDirectory()
        {
            string root = Path.GetDirectoryName(Application.dataPath);
            return Path.Combine(string.IsNullOrEmpty(root) ? "." : root, "Screenshots");
        }

        private static string Unique(HashSet<string> used, string location)
        {
            string slug = string.IsNullOrEmpty(location) ? "location" : location;
            if (used.Add(slug))
            {
                return slug;
            }

            int i = 2;
            string candidate;
            do
            {
                candidate = slug + "_" + i;
                i++;
            }
            while (!used.Add(candidate));

            return candidate;
        }

        private static string Slug(string raw)
        {
            if (string.IsNullOrEmpty(raw))
            {
                return "location";
            }

            var chars = new char[raw.Length];
            int n = 0;
            bool prevUnderscore = false;
            foreach (char c in raw.Trim())
            {
                char o;
                if (char.IsLetterOrDigit(c) || c == '-' || c == '_')
                {
                    o = c;
                }
                else if (char.IsWhiteSpace(c) || c == '/' || c == '\\')
                {
                    o = '_';
                }
                else
                {
                    continue;
                }

                if (o == '_' && prevUnderscore)
                {
                    continue;
                }

                chars[n++] = o;
                prevUnderscore = o == '_';
            }

            if (n == 0)
            {
                return "location";
            }

            return new string(chars, 0, n).Trim('_');
        }
    }
}
